### ISSUE TITLE
Core Milestone Clean Up

### ISSUE THREAD

**Issue by wsdOgawa** [WebServiceDevelopment/PrivateInvoice#15]
As I'm going through the issues required for milestone 1, I'm making a list of smaller issues that need to be tied up before the core release. 

### ETH Address
- [x] Generate ETH address on signup
- [x] Add ganache funds to user on signup
- [x] Add ETH address to contact information

### Organization
- [ ] move config.json to .env
- [x] move modules out of routes
- [x] Split between organization and member

### Contacts
- [x] consume invite code after it has been used

### Verification
- [x] Make sure presentations verify
- [x] Make sure credentials verify
- [ ] change from did:key to did:elem

### Documentation
- [ ] add documentation for ganache and sidetree

**Comment by wsdOgawa** [comment]
I think we're good for a release. This is about where I wanted to be with Swagger, Postman tests, and application mechanics. Since things are stable. I'm going to go ahead and close this and open a separate set of issues that focus specifically on Jest tests.
